#!/bin/bash
#====================================
# @file   : cibuild
# @brief  : Builds the docker images
#           in the context of CI/CD (Travis)
# @usage  : script/cibuild
# @param  : none
#====================================
# Copyright (C) 2020 Stephen G. Tuggy <sgt@stephengtuggy.com>
#
# This file is part of Vega Strike.
#
# Vega Strike is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Vega Strike is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Vega Strike.  If not, see <https://www.gnu.org/licenses/>.

set -e

DOCKER_IMG_NAME="vegastrike/vega-strike-build-env:$(echo $FROM | sed 's/:/_/' | sed 's/\//_/')"
docker build --build-arg from=$FROM -t $DOCKER_IMG_NAME .
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push $DOCKER_IMG_NAME

echo "cibuild Done!"
