name: Anchore-Container-Scan
permissions:
  contents: read
  pull-requests: read
  security-events: write

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        FROM:
          - 'ubuntu:questing'
          - 'ubuntu:plucky'
          - 'ubuntu:noble'
          #- 'linuxmintd/mint22.2-amd64'
          #- 'linuxmintd/mint22-amd64'
          - 'debian:trixie'
          - 'debian:bookworm'
          - 'opensuse/leap:16.0'
          - 'opensuse/leap:15.6'
          - 'fedora:43'
          - 'fedora:42'
          - 'rockylinux/rockylinux:10.1'
          - 'rockylinux/rockylinux:10.0'
          - 'rockylinux/rockylinux:9.7'
          - 'rockylinux/rockylinux:9.6'
          - 'manjarolinux/base'
          - 'dhi.io/python:3.14.3-debian13-dev'
          - 'dhi.io/python:3.14-debian13-dev'
          - 'dhi.io/python:3.13.12-debian13-dev'
          - 'dhi.io/python:3.13-debian13-dev'
          # - 'alex5402/endeavouros'
          # - 'funtoo/stage3-generic_64'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          submodules: false

      # - name: Run CI
      #   env:
      #     FROM:       ${{ matrix.FROM }}
      #     IS_RELEASE: 0
      #   run: script/cibuild

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd #v4.0.0
        env:
          FROM:       ${{ matrix.FROM }}
          IS_RELEASE: 0

      - name: Build local container
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 #v7.0.0
        env:
          FROM:       ${{ matrix.FROM }}
          IS_RELEASE: 0
        with:
          build-args: from=${{ matrix.FROM }}
          tags: localbuild/${{ matrix.FROM }}
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@7037fa011853d5a11690026fb85feee79f4c946c #v7.3.2
        id: scan
        with:
          image: "image:localbuild/${{ matrix.FROM }}"
          fail-build: false
          severity-cutoff: critical

      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@17783bfb99b07f70fae080b654aed0c514057477 #v4.30.9
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
