name: Linux - Release
permissions:
  contents: read
  pull-requests: read

on:
  release:
    types:
      - created
      - edited

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment:
      name: production

    strategy:
      fail-fast: false
      matrix:
        FROM:
          - 'ubuntu:resolute'
          - 'ubuntu:questing'
          - 'ubuntu:plucky'
          - 'ubuntu:noble'
          - 'linuxmintd/mint22.3-amd64'
          - 'linuxmintd/mint22.2-amd64'
          - 'linuxmintd/mint22-amd64'
          - 'debian:trixie'
          - 'debian:bookworm'
          - 'opensuse/leap:16.0'
          - 'opensuse/leap:15.6'
          - 'fedora:44'
          - 'fedora:43'
          - 'fedora:42'
          - 'rockylinux/rockylinux:10.1'
          - 'rockylinux/rockylinux:10.0'
          - 'rockylinux/rockylinux:9.7'
          - 'rockylinux/rockylinux:9.6'
          - 'manjarolinux/base'
          - 'alex5402/endeavouros'
          - 'dhi.io/python:3.14.3-debian13-dev'
          - 'dhi.io/python:3.14-debian13-dev'
          - 'dhi.io/python:3.13.12-debian13-dev'
          - 'dhi.io/python:3.13-debian13-dev'
          #- 'funtoo/stage3-generic_64'

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 2
        submodules: false

    - name: Extract tag name etc
      shell: bash
      run: |
        echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV

    - name: Test tag name etc
      run: |
        echo "${TAG_NAME}"

    - name: Docker Login
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 #v4.1.0
      with:
        username: "${{ secrets.DOCKER_HUB_USER }}"
        password: "${{ secrets.DOCKER_HUB_KEY }}"
        logout: true

    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        IS_RELEASE: 1
      run: script/cibuild
